parameters:
    sm_chat.stripe.api_key: sk_test_TfK0OV6ZYMqwD4U0rLB6Z81X

services:
    sm_chat.stripe:
        class: SM\ChatBundle\PaymentMethod\StripePaymentMethod
        arguments:
            - @doctrine.orm.entity_manager
            - %sm_chat.stripe.api_key%