parameters:
#    sm_wallet.example.class: SM\WalletBundle\Example

    sm_wallet.tip_jar_config:
        tip_jar_options: [1, 3, 5, 10, 20, 50, 100]

services:
#    sm_wallet.example:
#        class: %sm_wallet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    sm_wallet.tip_jar:
        class: SM\WalletBundle\TipJar\TipJar
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%sm_wallet.tip_jar_config%"

    sm_wallet.token_service:
        class: SM\WalletBundle\Token\TokenService
        arguments:
            - "@doctrine.orm.entity_manager"